config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def ask
  end

  def answer
    if params['question_to_coach'] == 'I am going to work'
      @answer = 'Great!'
    elsif params['question_to_coach'][-1] == '?'
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<%# If the message is I am going to work, the coach will answer Great! %>
<%# If the message has a question mark ? at the end, the coach will answer Silly question, get dressed and go to work!. %>
<%# Otherwise the coach will answer I don't care, get dressed and go to work! %>

<h1>Stupid Coaching</h1>

<div class="question-block">
<p><%=params['question_to_coach']%></p>
<p> -You</p>
</div>

<div class="answer-block">
<p><%= @answer%></p>
<p>-The coach</p>
</div>


<%= link_to ask_path do%>
 <div class="button_link">Ask again</div>
<%end%>

app/views/questions/ask.html.erb
<h2>Ask your coach anything:</h2>
<form action="/answer">
  <input type="text" name="question_to_coach">
  <input type="submit" value="Ask!" class= "button_link_small">
</form>